image: node:12.16.3-stretch-slim

stages:
   - build
   - verify
   - pack
   - store

build:
  tags:
    - docker-runner
  stage: build
  script:
    - node --version
    - npm --version
    - yarn --version
    - yarn --network-timeout 600000
    - yarn build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
      - build
    policy: push
  only: ['development', 'qa', 'tags', '/^v.*x$/i']

audit:
  tags:
    - docker-runner
  stage: verify
  script:
    - yarn audit:production
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
    policy: pull
  only: ['development', 'qa', 'tags', '/^v.*x$/i']

lint:
  tags:
    - docker-runner
  stage: verify
  script:
    - yarn lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
    policy: pull
  only: ['development', 'qa', 'tags', '/^v.*x$/i']

test:
  tags:
    - docker-runner
  stage: verify
  script:
    - yarn test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
    policy: pull
  only: ['development', 'qa', 'tags', '/^v.*x$/i']

pack:
  tags:
    - docker-runner
  stage: pack
  script:
    - echo "$(date +"%d-%m-%Y %H:%M:%S") - Short commit SHA ${CI_COMMIT_SHA:0:8} - Long commit SHA $CI_COMMIT_SHA - Project name $CI_PROJECT_NAME - Branch name $CI_COMMIT_REF_NAME" >> build/$CI_PROJECT_NAME-build.info
    - tar zcf $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHA:0:8}.tgz -C ./build/ .
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - build
    policy: pull
  only: ['development', 'qa', 'tags', '/^v.*x$/i']
  artifacts:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHA:0:8}.tgz
    expire_in: 1 day

store-artifacts:
  tags:
    - shell-runner
  stage: store
  script:
    - sudo cp $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHA:0:8}.tgz /opt/affectli/artifacts/
  only: ['development', 'qa', 'tags', '/^v.*x$/i']
  variables:
    GIT_STRATEGY: none
